### ISSUE TITLE
Create tags collection

### ISSUE THREAD

**Issue by NewtonICS** [geostudy/geostudy-source#27]
Please do work for this task in a branch named issue-27.

Set up a Tags collection for App database to allow users to select tags relevant to their Spot for ease of search functionality and comparison.

Initialize at least 10 starting tags to work with.

**Comment by mhkfchun** [comment]
Tags collection created.

**Comment by mhkfchun** [comment]
![image](https://user-images.githubusercontent.com/60207632/80113664-4fa5cb00-851e-11ea-95a7-64ba8f07f1ce.png)
